version: '3.8'

services:
  back-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        REACT_APP_BACKEND_URL: 'http://localhost:8000'
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb-dev
    environment:
      CORS_ORIGIN: http://localhost:3000
      BACKEND_URL: http://localhost:8000
      PORT: 8000
      MONGODB_URI: mongodb-dev://admin:pass@mongodb-dev:27017
      SMTP_SERVER: smtp-relay.brevo.com
      SMTP_LOGIN: 752df5001@smtp-brevo.com
      SMTP_PASSWORD: VJTrWhBxcnaUMSs9
    networks:
      - app_network
    profiles:
      - dev

  back-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        REACT_APP_BACKEND_URL: 'https://vududu.ru'
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb-prod
    environment:
      BACKEND_URL: https://vududu.ru
      PORT: 8000
      MONGODB_URI: mongodb-prod://admin:pass@mongodb-prod:27017/
      SMTP_SERVER: smtp-relay.brevo.com
      SMTP_LOGIN: 752df5001@smtp-brevo.com
      SMTP_PASSWORD: VJTrWhBxcnaUMSs9
    networks:
      - app_network
    profiles:
      - prod

  mongodb-dev:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    profiles:
      - dev

  mongodb-prod:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    profiles:
      - prod

  mongo-express-dev:
    image: mongo-express:latest
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb-dev://admin:pass@mongodb-dev:27017/

    depends_on:
      - mongodb-dev
    networks:
      - app_network
    profiles:
      - dev

  mongo-express-prod:
    image: mongo-express:latest
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-prod
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb-prod://admin:pass@mongodb-prod:27017/

    depends_on:
      - mongodb-prod
    networks:
      - app_network
    profiles:
      - prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back-prod
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_network
    profiles:
      - prod

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    profiles:
    - prod

volumes:
  mongodb_data:
  certbot-etc:

networks:
  app_network:
    driver: bridge
