version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      PORT: 8000
      CORS_ORIGIN: ${CORS_ORIGIN}
      BACKEND_URL: ${BACKEND_URL}
      MONGODB_URI: ${MONGODB_URI}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - app_network
    profiles:
      - dev
      - prod

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    profiles:
      - dev
      - prod

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
#    restart: always

    environment:

      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

    depends_on:
      - mongo
    networks:
      - app_network
    profiles:
      - dev
      - prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    depends_on:
      - back
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_network
    profiles:
      - prod

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    profiles:
    - prod

volumes:
  mongo_data:
  certbot-etc:

networks:
  app_network:
    driver: bridge
