version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
#        REACT_APP_BACKEND_URL: 'http://localhost:8000'
        REACT_APP_BACKEND_URL: 'http://vududu.ru'
    restart: always
    ports:
#      - 8000:8000
      - 80:8000
    depends_on:
      - mongodb
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://admin:pass@mongodb:27017
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"

    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Исправлено имя хоста на mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongodb:27017/

    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
