export enum Paths {
  events = '/events/planned',
  history = '/events/history',
  contacts = '/contacts',
  documents = '/documents',
  dogs = '/dogs/all',
  dog_creator = '/dogs/create-dog',
  dog = '/dogs/dog/:id',
  dog_editor = '/dogs/dog/:id/editor',

  litters = '/litters',
  litter_creator = '/litters/create-litter',
  litter = '/litters/litter/:id',
  litter_editor = '/litters/litter/:id/editor',
  profile = '/profile',
  settings = '/settings',
  sign_in = '/sign-in',
  sign_up = '/sign-up',
  confirmEmail = '/confirm-email',
  createProfile = '/create-profile',
  event = '/events/:id',
  document = '/document/:id',
  event_editor = '/events/:id/editor',
  pedigrees = '/pedigrees',
  passwordRecovery = '/password-recovery',
  passwordRecoveryFinish = '/password-recovery/:recoveryToken',
}

export const PublicRoutes = [
  Paths.sign_in,
  Paths.sign_up,
  Paths.confirmEmail,
  Paths.passwordRecovery,
  Paths.passwordRecoveryFinish,
] as const;

export const PrivateRoutes = [
  Paths.events,
  Paths.history,
  Paths.contacts,
  Paths.documents,
  Paths.dogs,
  Paths.profile,
  Paths.dog,
  Paths.dog_editor,
  Paths.dog_creator,
  Paths.litters,
  Paths.litter,
  Paths.litter_editor,
  Paths.litter_creator,
  Paths.event,
  Paths.event_editor,
  Paths.pedigrees,
  Paths.createProfile,
  // Paths.event,
  // Paths.document,
 // Paths.settings,
];
