export const DB_NAME = 'breeder_crm'

export enum COLLECTIONS {
  USERS = 'USERS',
  KENNELS = 'KENNELS',
  BREEDERS = 'BREEDERS',
  LITTERS = 'LITTERS',
  LITTER_HISTORIES = 'LITTER_HISTORIES',
  // DOG_CLUBS = 'DOG_CLUBS',
  DOGS = 'DOGS',
  CONTACTS = 'CONTACTS',
  CONTACT_LISTS = 'CONTACT_LISTS',
  DOCUMENTS = 'DOCUMENTS',
  TREATMENTS = 'TREATMENTS',
  TREATMENT_HISTORIES = 'TREATMENT_HISTORIES',
  DIAGNOSTICS = 'DIAGNOSTICS',
  DIAGNOSTIC_HISTORIES = 'DIAGNOSTIC_HISTORIES',
  HEATS = 'HEATS',
  HEAT_HISTORIES = 'HEAT_HISTORIES',
  MATES = 'MATES',
  MATE_HISTORIES = 'MATE_HISTORIES',
  BIRTHS = 'BIRTHS',
  BIRTH_HISTORIES = 'BIRTH_HISTORIES',
  REGISTRATIONS = 'REGISTRATIONS',
  PROFILES = 'PROFILES',
  EVENTS = 'EVENTS',
  STUD_DOGS = 'STUD_DOGS',
}

export enum FIELDS_NAMES {
  DIAGNOSTIC_HISTORY_ID = 'diagnosticsHistoryId',
  TREATMENT_HISTORY_ID = 'treatmentHistoryId',
  HEAT_HISTORY_ID = 'heatHistoryId',
  MATE_HISTORY_ID = 'mateHistoryId',
  BIRTH_HISTORY_ID = 'birthHistoryId',
  LITTER_HISTORY_ID = 'litterHistoryId',
  REGISTRATION_ID = 'registrationId',
  BREEDER_ID = 'breederId',
  KENNEL_ID = 'kennelId',
  LIST = 'list',
  CONTACTS = 'contacts',
  DOGS_IDS = 'dogIds',
  IS_ACTIVATED = 'isActivated',
  CONTACT_LIST_ID = 'contactListId',
  PROFILES_IDS = 'profileIds',
  ID = '_id',
  REPRODUCTIVE_HISTORY = 'reproductiveHistory',
  LITTER_IDS = 'litterIds',
  REPRODUCTIVE_HISTORY_LITTER_IDS = 'reproductiveHistory.litterIds',
  REPRODUCTIVE_HISTORY_MATE_IDS = 'reproductiveHistory.mateIds',
  REPRODUCTIVE_HISTORY_HEAT_IDS = 'reproductiveHistory.heatIds',
  CONTACT_IDS = 'contactIds',
  TREATMENT_IDS = 'treatmentIds',
  EVENT_IDS = 'eventIds',
  DIAGNOSTIC_IDS = 'diagnosticIds',
  REPRODUCTIVE_HISTORY_BIRTH_IDS = 'reproductiveHistory.birthIds',
  PROFILE_ID = 'profileId',
  ACTIVE_PROFILE_ID = 'activeProfileId',
  NAME = 'name',
  FULL_NAME = 'fullName',
  DATE_OF_BIRTH = 'dateOfBirth',
  BREED = 'breed',
  GENDER = 'gender',
  MICROCHIP_NUMBER = 'microchipNumber',
  TATTOO_NUMBER = 'tattooNumber',
  COLOR = 'color',
  IS_NEUTERED = 'isNeutered',
  LITTER_TITLE = 'litterTitle',
  PUPPY_IDS = 'puppyIds',
  LITTER_ID = 'litterId',
}


// export const BASE_DOG_INFO_FIELD_NAMES = [
//   FIELDS_NAMES.NAME,
//   FIELDS_NAMES.FULL_NAME,
//   FIELDS_NAMES.DATE_OF_BIRTH,
//   FIELDS_NAMES.BREED,
//   FIELDS_NAMES.GENDER,
//   FIELDS_NAMES.MICROCHIP_NUMBER,
//   FIELDS_NAMES.TATTOO_NUMBER,
//   FIELDS_NAMES.COLOR,
//   FIELDS_NAMES.IS_NEUTERED,
//   FIELDS_NAMES.LITTER_TITLE,
// ] as const

// не уверена, что эта константа нужна, потому что path вроде только в одном месте указывается в каждом случае
// export const PATHS = {
//   DIAGNOSTICS: '/diagnostics',
//
// }
