import {ObjectId} from 'mongodb'
import {FIELDS_NAMES} from "../constants";
import {ClientDog} from "./dog";
import {ClientLitter} from "./litter";
import {ClientDocument} from "./document";

export enum PERMISSION_GROUPS {
  ORGANISATION = 'organisation',
  REGISTERED = 'registered',
  ALL = 'all',
}

export enum DATA_GROUPS {
  PUBLIC = 'public',
  PROTECTED = 'protected',
  PRIVATE = 'private',
}

export type Permissions = {
  viewers: {
    [DATA_GROUPS.PUBLIC]: {
      group: PERMISSION_GROUPS.ORGANISATION | PERMISSION_GROUPS.REGISTERED | PERMISSION_GROUPS.ALL | null,
      profileIds: ObjectId[]
    };
    [DATA_GROUPS.PROTECTED]: {
      group: PERMISSION_GROUPS.ORGANISATION | PERMISSION_GROUPS.REGISTERED | PERMISSION_GROUPS.ALL | null,
      profileIds: ObjectId[]
    };
    [DATA_GROUPS.PRIVATE]: {
      group: null,
      profileIds: ObjectId[]
    };
  }
  editors: Record<DATA_GROUPS, {group: null, profileIds: ObjectId[]}>
}

export type ProfilePermissionsByEntity = { view: Record<DATA_GROUPS, boolean>, edit: Record<DATA_GROUPS, boolean> }

export const DogDataGroupsByFieldName: Record<keyof Omit<ClientDog, 'permissions'>, DATA_GROUPS> = {
  [FIELDS_NAMES.ID]: DATA_GROUPS.PUBLIC, // ?? айдишник является защищенной информацией или доступен всем?
  [FIELDS_NAMES.NAME]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.FULL_NAME]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.DATE_OF_BIRTH]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.DATE_OF_DEATH]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.BREED_ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.GENDER]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.COLOR]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.IS_NEUTERED]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.OWNER_PROFILE_ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.OWNER_PROFILE_NAME]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.FEDERATION_ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.LITTER_DATA]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.REPRODUCTIVE_HISTORY]: DATA_GROUPS.PUBLIC,

  [FIELDS_NAMES.MICROCHIP_NUMBER]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.TATTOO_NUMBER]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.PEDIGREE_NUMBER]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.PEDIGREE_ID]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.BREEDER_PROFILE_ID]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.HEALTH_CERTIFICATES]: DATA_GROUPS.PROTECTED,

  [FIELDS_NAMES.PUPPY_CARD_NUMBER]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.PUPPY_CARD_ID]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.DIAGNOSTICS]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.CREATOR_PROFILE_ID]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.CREATOR_PROFILE_NAME]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.TREATMENTS]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.VACCINATIONS]: DATA_GROUPS.PRIVATE,
}

export const LitterDataGroupsByFieldName: Record<keyof Omit<ClientLitter, 'permissions'>, DATA_GROUPS> = {
  [FIELDS_NAMES.ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.FEDERATION_ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.FATHER_DATA]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.MOTHER_DATA]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.LITTER_TITLE]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.DATE_OF_BIRTH]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.BREED_ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.PUPPY_IDS]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.VERIFIED_PUPPY_IDS]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.VERIFIED]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.LITTER_SUMMARY]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.PUPPIES_DATA]: DATA_GROUPS.PUBLIC,

  [FIELDS_NAMES.CREATOR_PROFILE_ID]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.CREATOR_PROFILE_NAME]: DATA_GROUPS.PRIVATE,
  [FIELDS_NAMES.COMMENTS]: DATA_GROUPS.PRIVATE,
}

export const DocumentDataGroupsByFieldName: Record<keyof Omit<ClientDocument, 'permissions'>, DATA_GROUPS> = {
  [FIELDS_NAMES.ID]: DATA_GROUPS.PUBLIC,
  [FIELDS_NAMES.PROFILE_ID]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.DOGS_IDS]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.LITTER_ID]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.EVENT_ID]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.LINK]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.TYPE]: DATA_GROUPS.PROTECTED,
  [FIELDS_NAMES.DATA]: DATA_GROUPS.PROTECTED,
}
