version: "3.9"
services:
  memmap-server:
    container_name: server
    build:
      context: .
    restart: always
    ports:
      - "${PORT}:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - backend
    volumes:
      - .:/usr/app/server

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"

    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Исправлено имя хоста на mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass

    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
